// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cgroupSkbSockinfo struct {
	_    structs.HostLayout
	Comm [16]uint8
	Pid  int32
}

type cgroupSkbStatkey struct {
	_     structs.HostLayout
	Srcip struct {
		_    structs.HostLayout
		In6U struct {
			_       structs.HostLayout
			U6Addr8 [16]uint8
		}
	}
	Dstip struct {
		_    structs.HostLayout
		In6U struct {
			_       structs.HostLayout
			U6Addr8 [16]uint8
		}
	}
	Cgroupid uint64
	Comm     [16]int8
	Pid      int32
	SrcPort  uint16
	DstPort  uint16
	Proto    uint8
	_        [7]byte
}

type cgroupSkbStatvalue struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

// loadCgroupSkb returns the embedded CollectionSpec for cgroupSkb.
func loadCgroupSkb() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CgroupSkbBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cgroupSkb: %w", err)
	}

	return spec, err
}

// loadCgroupSkbObjects loads cgroupSkb and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cgroupSkbObjects
//	*cgroupSkbPrograms
//	*cgroupSkbMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCgroupSkbObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCgroupSkb()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cgroupSkbSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupSkbSpecs struct {
	cgroupSkbProgramSpecs
	cgroupSkbMapSpecs
	cgroupSkbVariableSpecs
}

// cgroupSkbProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupSkbProgramSpecs struct {
	CgroupSkbEgress  *ebpf.ProgramSpec `ebpf:"cgroup_skb_egress"`
	CgroupSkbIngress *ebpf.ProgramSpec `ebpf:"cgroup_skb_ingress"`
	CgroupSockCreate *ebpf.ProgramSpec `ebpf:"cgroup_sock_create"`
}

// cgroupSkbMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupSkbMapSpecs struct {
	PktCount *ebpf.MapSpec `ebpf:"pkt_count"`
	SockInfo *ebpf.MapSpec `ebpf:"sock_info"`
}

// cgroupSkbVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupSkbVariableSpecs struct {
}

// cgroupSkbObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCgroupSkbObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupSkbObjects struct {
	cgroupSkbPrograms
	cgroupSkbMaps
	cgroupSkbVariables
}

func (o *cgroupSkbObjects) Close() error {
	return _CgroupSkbClose(
		&o.cgroupSkbPrograms,
		&o.cgroupSkbMaps,
	)
}

// cgroupSkbMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCgroupSkbObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupSkbMaps struct {
	PktCount *ebpf.Map `ebpf:"pkt_count"`
	SockInfo *ebpf.Map `ebpf:"sock_info"`
}

func (m *cgroupSkbMaps) Close() error {
	return _CgroupSkbClose(
		m.PktCount,
		m.SockInfo,
	)
}

// cgroupSkbVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCgroupSkbObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupSkbVariables struct {
}

// cgroupSkbPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCgroupSkbObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupSkbPrograms struct {
	CgroupSkbEgress  *ebpf.Program `ebpf:"cgroup_skb_egress"`
	CgroupSkbIngress *ebpf.Program `ebpf:"cgroup_skb_ingress"`
	CgroupSockCreate *ebpf.Program `ebpf:"cgroup_sock_create"`
}

func (p *cgroupSkbPrograms) Close() error {
	return _CgroupSkbClose(
		p.CgroupSkbEgress,
		p.CgroupSkbIngress,
		p.CgroupSockCreate,
	)
}

func _CgroupSkbClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cgroupskb_x86_bpfel.o
var _CgroupSkbBytes []byte
