// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type kprobeStatkey struct {
	_     structs.HostLayout
	Srcip struct {
		_    structs.HostLayout
		In6U struct {
			_       structs.HostLayout
			U6Addr8 [16]uint8
		}
	}
	Dstip struct {
		_    structs.HostLayout
		In6U struct {
			_       structs.HostLayout
			U6Addr8 [16]uint8
		}
	}
	Cgroupid uint64
	Comm     [16]int8
	Pid      int32
	SrcPort  uint16
	DstPort  uint16
	Proto    uint8
	_        [7]byte
}

type kprobeStatvalue struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

// loadKprobe returns the embedded CollectionSpec for kprobe.
func loadKprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kprobe: %w", err)
	}

	return spec, err
}

// loadKprobeObjects loads kprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kprobeObjects
//	*kprobePrograms
//	*kprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadKprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kprobeSpecs struct {
	kprobeProgramSpecs
	kprobeMapSpecs
	kprobeVariableSpecs
}

// kprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kprobeProgramSpecs struct {
	IcmpSend       *ebpf.ProgramSpec `ebpf:"__icmp_send"`
	Icmp6Send      *ebpf.ProgramSpec `ebpf:"icmp6_send"`
	IcmpRcv        *ebpf.ProgramSpec `ebpf:"icmp_rcv"`
	Icmpv6Rcv      *ebpf.ProgramSpec `ebpf:"icmpv6_rcv"`
	Ip6SendSkb     *ebpf.ProgramSpec `ebpf:"ip6_send_skb"`
	IpSendSkb      *ebpf.ProgramSpec `ebpf:"ip_send_skb"`
	SkbConsumeUdp  *ebpf.ProgramSpec `ebpf:"skb_consume_udp"`
	TcpCleanupRbuf *ebpf.ProgramSpec `ebpf:"tcp_cleanup_rbuf"`
	TcpSendmsg     *ebpf.ProgramSpec `ebpf:"tcp_sendmsg"`
}

// kprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kprobeMapSpecs struct {
	PktCount *ebpf.MapSpec `ebpf:"pkt_count"`
}

// kprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kprobeVariableSpecs struct {
}

// kprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type kprobeObjects struct {
	kprobePrograms
	kprobeMaps
	kprobeVariables
}

func (o *kprobeObjects) Close() error {
	return _KprobeClose(
		&o.kprobePrograms,
		&o.kprobeMaps,
	)
}

// kprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type kprobeMaps struct {
	PktCount *ebpf.Map `ebpf:"pkt_count"`
}

func (m *kprobeMaps) Close() error {
	return _KprobeClose(
		m.PktCount,
	)
}

// kprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type kprobeVariables struct {
}

// kprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type kprobePrograms struct {
	IcmpSend       *ebpf.Program `ebpf:"__icmp_send"`
	Icmp6Send      *ebpf.Program `ebpf:"icmp6_send"`
	IcmpRcv        *ebpf.Program `ebpf:"icmp_rcv"`
	Icmpv6Rcv      *ebpf.Program `ebpf:"icmpv6_rcv"`
	Ip6SendSkb     *ebpf.Program `ebpf:"ip6_send_skb"`
	IpSendSkb      *ebpf.Program `ebpf:"ip_send_skb"`
	SkbConsumeUdp  *ebpf.Program `ebpf:"skb_consume_udp"`
	TcpCleanupRbuf *ebpf.Program `ebpf:"tcp_cleanup_rbuf"`
	TcpSendmsg     *ebpf.Program `ebpf:"tcp_sendmsg"`
}

func (p *kprobePrograms) Close() error {
	return _KprobeClose(
		p.IcmpSend,
		p.Icmp6Send,
		p.IcmpRcv,
		p.Icmpv6Rcv,
		p.Ip6SendSkb,
		p.IpSendSkb,
		p.SkbConsumeUdp,
		p.TcpCleanupRbuf,
		p.TcpSendmsg,
	)
}

func _KprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kprobe_arm64_bpfel.o
var _KprobeBytes []byte
