name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-22.04
          - arch: aarch64
            runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory $(pwd) # Workaround for fatal: detected dubious ownership in repository at '/__w/reliability-matrix/reliability-matrix'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libbpf-dev
      - run: make generate build VERSION=${{ github.ref_name }}
      - run: mv ./pktstat-bpf ./pktstat-bpf-${{ matrix.arch }}
      - name: Upload ${{ matrix.arch }} binary
        uses: actions/upload-artifact@v4
        with:
          name: pktstat-bpf-${{ matrix.arch }}
          path: ./pktstat-bpf-${{ matrix.arch }}

  create-release:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Download x86_64 binary
        uses: actions/download-artifact@v4
        with:
          name: pktstat-bpf-x86_64
          path: ./bin
      - name: Download aarch64 binary
        uses: actions/download-artifact@v4
        with:
          name: pktstat-bpf-aarch64
          path: ./bin
      - name: Create GitHub Release
        run: |
          gh release create ${{ github.ref_name }} ./bin/pktstat-bpf-* --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
